name: base
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.3.3
  curl_logger_dio_interceptor: ^1.0.0
  pretty_dio_logger: ^1.3.1
  http_parser: ^4.0.2
  path: ^1.8.3
  device_info_plus: ^9.1.0
  android_id: ^0.3.6
  package_info_plus: ^4.0.2
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  intl_utils: ^2.8.5

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7

  # notification
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.3
  firebase_core: ^2.21.0
  firebase_messaging_platform_interface: ^4.5.12
  firebase_crashlytics: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_intl:
  enable: true
  class_name: S
  arb_dir: lib/res/l10n
  output_dir: lib/res/l10n

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
